openapi: 3.0.0
info:
  title: Adoption Request List Service API
  version: 1.0.0
  description: This API provides adoption request listing functionality for the Shaggy Mission pet adoption system. The service enables administrators and staff to view and manage adoption requests with pagination support, allowing efficient browsing of all submitted adoption requests in the system.

paths:
  /list/adoption-requests:
    get:
      summary: Get paginated list of adoption requests
      description: Retrieves a paginated list of adoption requests sorted by date requested (newest first). Returns adoption request details along with pagination metadata to support administrative interfaces and management dashboards.
      tags:
        - Adoption Request List
      parameters:
        - name: page
          in: query
          required: false
          description: Page number for pagination (default 1)
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 1
      responses:
        '200':
          description: Successfully retrieved adoption requests list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdoptionRequestListResponse'
              examples:
                first_page:
                  summary: First page of adoption requests
                  value:
                    currentPage: 1
                    totalPages: 5
                    totalRequests: 47
                    requests:
                      - _id: "64f8b2a1c3d4e5f6a7b8c9d3"
                        userId: "user123"
                        petId: "64f8b2a1c3d4e5f6a7b8c9d0"
                        message: "I would love to provide a loving home for this pet."
                        status: "pending"
                        dateRequested: "2024-01-15T10:30:00.000Z"
                      - _id: "64f8b2a1c3d4e5f6a7b8c9d4"
                        userId: "user456"
                        petId: "64f8b2a1c3d4e5f6a7b8c9d1"
                        status: "approved"
                        dateRequested: "2024-01-14T15:20:00.000Z"
                second_page:
                  summary: Second page of adoption requests
                  value:
                    currentPage: 2
                    totalPages: 5
                    totalRequests: 47
                    requests:
                      - _id: "64f8b2a1c3d4e5f6a7b8c9d5"
                        userId: "user789"
                        petId: "64f8b2a1c3d4e5f6a7b8c9d2"
                        message: "Our family is ready to welcome a new pet."
                        status: "rejected"
                        dateRequested: "2024-01-13T09:45:00.000Z"
        '500':
          description: Internal Server Error – Database connection error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                server_error:
                  summary: Database connection error
                  value:
                    message: "Server error"

components:
  schemas:
    AdoptionRequestListResponse:
      type: object
      properties:
        currentPage:
          type: integer
          description: Current page number
          example: 1
          minimum: 1
        totalPages:
          type: integer
          description: Total number of pages available
          example: 5
          minimum: 0
        totalRequests:
          type: integer
          description: Total number of adoption requests in the system
          example: 47
          minimum: 0
        requests:
          type: array
          description: Array of adoption requests for the current page
          items:
            $ref: '#/components/schemas/AdoptionRequest'
          maxItems: 10
      required:
        - currentPage
        - totalPages
        - totalRequests
        - requests
      description: Response containing paginated adoption requests list

    AdoptionRequest:
      type: object
      properties:
        _id:
          type: string
          description: Unique MongoDB ObjectId for the adoption request
          example: "64f8b2a1c3d4e5f6a7b8c9d3"
          pattern: '^[0-9a-fA-F]{24}$'
        userId:
          type: string
          description: Unique identifier for the user who made the request
          example: "user123"
        petId:
          type: string
          description: Unique identifier for the requested pet
          example: "64f8b2a1c3d4e5f6a7b8c9d0"
          pattern: '^[0-9a-fA-F]{24}$'
        message:
          type: string
          description: Personal message from the adopter
          example: "I would love to provide a loving home for this pet."
          nullable: true
        status:
          type: string
          description: Current status of the adoption request
          enum: ["pending", "approved", "rejected"]
          example: "pending"
        dateRequested:
          type: string
          format: date-time
          description: Timestamp when the adoption request was submitted
          example: "2024-01-15T10:30:00.000Z"
      required:
        - _id
        - userId
        - petId
        - status
        - dateRequested
      description: Individual adoption request record

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message describing what went wrong
          example: "Server error"
      required:
        - message
      description: Standard error response format

    AdoptionRequestStatus:
      type: string
      enum: ["pending", "approved", "rejected"]
      description: Possible statuses for an adoption request - pending (submitted awaiting review), approved (approved by staff), rejected (declined or pet no longer available)
      example: "pending"

  parameters:
    PageParam:
      name: page
      in: query
      required: false
      description: Page number for pagination
      schema:
        type: integer
        minimum: 1
        default: 1
        example: 1

tags:
  - name: Adoption Request List
    description: Operations for listing and browsing adoption requests